feat: add dependencies check

diff --git a/install b/install
--- a/install
+++ b/install
@@ -12,14 +12,21 @@ core() {
     exit 0
   fi
 
-  install
-  if [ $? -eq 0 ]; then
-    log::success "install ${PACKAGE_NAME} success."
-    exit 0
-  else
-    log::error "install ${PACKAGE_NAME} failed."
-    exit 1
+  log::info "[$(timestamp)] checking dependencies ..."
+  check_dependencies
+  if [ "$?" != "0" ]; then
+    log::error "[$(timestamp)] failed to checking dependencies."
+    return 1
   fi
+
+  install
+  if [ "$?" != "0" ]; then
+    log::error "[$(timestamp)] failed toinstall ${PACKAGE_NAME}."
+    return 1
+
+  fi
+
+  log::success "[$(timestamp)] succeed to install ${PACKAGE_NAME}."
 }
 
 run() {
@@ -35,6 +42,6 @@ if [ "$1" = "ONE_LINE" ]; then
   zmicro package install colima
 else
   set -e
-  
+
   run "$@"
 fi
